/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>

@class PSListController;

@interface PSBundleController : NSObject {
	PSListController *_parent;	// 4 = 0x4
}
- (id)initWithParentListController:(id)parentListController;	// 0x318bc994
- (void)load;	// 0x318bc984
- (id)specifiersWithSpecifier:(id)specifier;	// 0x318bc98c
- (void)unload;	// 0x318bc988
@end

