/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSTableCell.h"

@class UIImageView;

@interface PSImageCell : PSTableCell {
	UIImageView *_imageView;	// 100 = 0x64
}
- (void)drawTitleInRect:(CGRect)rect selected:(BOOL)selected;	// 0x318b4a54
- (void)setImageView:(id)view;	// 0x318b49ec
@end

