/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>


@interface PSKeychainUtilities : NSObject {
}
+ (id)_passwordForGenericAccount:(id)genericAccount service:(id)service;	// 0x318bd004
+ (id)_passwordForHost:(id)host username:(id)username port:(int)port protocol:(id)protocol;	// 0x318bca10
+ (id)passwordForHost:(id)host username:(id)username port:(int)port protocol:(id)protocol;	// 0x318bcbf0
+ (id)passwordForServiceName:(id)serviceName accountName:(id)name;	// 0x318bd198
+ (void)removePasswordForHost:(id)host username:(id)username port:(int)port protocol:(id)protocol;	// 0x318bce94
+ (void)removePasswordForServiceName:(id)serviceName accountName:(id)name;	// 0x318bd3b8
+ (void)setPassword:(id)password forHost:(id)host username:(id)username port:(int)port protocol:(id)protocol;	// 0x318bcc24
+ (void)setPassword:(id)password forServiceName:(id)serviceName accountName:(id)name;	// 0x318bd1c0
@end

