/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSEditingPane.h"

@class UISegmentedControl;

@interface PSMultiValueEditingPane : PSEditingPane {
	UISegmentedControl *_segmentedControl;	// 44 = 0x2c
}
@property(retain) id preferenceValue;	// G=0x318b6990; S=0x318b6904; converted property
- (id)initWithFrame:(CGRect)frame;	// 0x318b65e0
- (BOOL)drawLabel;	// 0x318b65d8
// converted property getter: - (id)preferenceValue;	// 0x318b6990
- (BOOL)requiresKeyboard;	// 0x318b65d0
- (void)segmentedControl:(id)control selectedSegmentChanged:(int)changed;	// 0x318b69f8
- (void)selectIndex:(int)index;	// 0x318b68d8
- (int)selectedIndex;	// 0x318b68ac
- (void)setPreferenceSpecifier:(id)specifier;	// 0x318b676c
// converted property setter: - (void)setPreferenceValue:(id)value;	// 0x318b6904
@end

