/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"


@interface PSSetupListController : PSListController {
}
- (void)setupAfterAnimateIn;	// 0x318bb068
- (void)setupBeforeAnimateIn;	// 0x318bb064
@end

