/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>

typedef enum PSCellType {
	PSGroupCell,
	PSLinkCell,
	PSLinkListCell,
	PSListItemCell,
	PSTitleValueCell,
	PSSliderCell,
	PSSwitchCell,
	PSStaticTextCell,
	PSEditTextCell,
	PSSegmentCell,
	PSGiantIconCell,
	PSGiantCell,
	PSSecureEditTextCell,
	PSButtonCell,
	PSEditTextViewCell,
} PSCellType;

@class NSMutableDictionary, NSDictionary, NSString, NSArray;

@interface PSSpecifier : NSObject {
	id target;	// 4 = 0x4
	SEL getter;	// 8 = 0x8
	SEL setter;	// 12 = 0xc
	SEL action;	// 16 = 0x10
	Class detailControllerClass;	// 20 = 0x14
	int cellType;	// 24 = 0x18
	Class editPaneClass;	// 28 = 0x1c
	int keyboardType;	// 32 = 0x20
	int autoCapsType;	// 36 = 0x24
	int autoCorrectionType;	// 40 = 0x28
	int textFieldType;	// 44 = 0x2c
	NSString *_name;	// 48 = 0x30
	NSArray *_values;	// 52 = 0x34
	NSDictionary *_titleDict;	// 56 = 0x38
	NSDictionary *_shortTitleDict;	// 60 = 0x3c
	id _userInfo;	// 64 = 0x40
	NSMutableDictionary *_properties;	// 68 = 0x44
}
@property(retain) NSString *name;	// G=0x318af5ec; S=0x318af6f8; converted property
@property(retain) NSMutableDictionary *properties;	// G=0x318aef68; S=0x318aef14; converted property
@property(retain) id shortTitleDictionary;	// G=0x318af628; S=0x318af824; converted property
@property(retain) id titleDictionary;	// G=0x318af614; S=0x318af7c0; converted property
@property(retain) id userInfo;	// G=0x318af600; S=0x318af75c; converted property
@property(retain) NSArray *values;	// G=0x318af6e4; S=0x318af888; converted property
+ (int)autoCapsTypeForString:(id)string;	// 0x318af4f8
+ (id)emptyGroupSpecifier;	// 0x318aee68
+ (id)groupSpecifierWithName:(id)name;	// 0x318aee20
+ (int)keyboardTypeForString:(id)string;	// 0x318af584
+ (id)preferenceSpecifierNamed:(id)named target:(id)target set:(SEL)set get:(SEL)get detail:(Class)detail cell:(int)cell edit:(Class)edit;	// 0x318aed3c
- (id)init;	// 0x318aecbc
- (void)dealloc;	// 0x318af330
- (id)description;	// 0x318af40c
- (id)identifier;	// 0x318af658
- (void)loadValuesAndTitlesFromDataSource;	// 0x318aef7c
// converted property getter: - (id)name;	// 0x318af5ec
// converted property getter: - (id)properties;	// 0x318aef68
- (id)propertyForKey:(id)key;	// 0x318aee88
- (void)removePropertyForKey:(id)key;	// 0x318aeee8
- (void)setKeyboardType:(int)type autoCaps:(int)caps autoCorrection:(int)correction;	// 0x318af900
// converted property setter: - (void)setName:(id)name;	// 0x318af6f8
// converted property setter: - (void)setProperties:(id)properties;	// 0x318aef14
- (void)setProperty:(id)property forKey:(id)key;	// 0x318aeeb4
// converted property setter: - (void)setShortTitleDictionary:(id)dictionary;	// 0x318af824
- (void)setTarget:(id)target;	// 0x318af8ec
// converted property setter: - (void)setTitleDictionary:(id)dictionary;	// 0x318af7c0
// converted property setter: - (void)setUserInfo:(id)info;	// 0x318af75c
// converted property setter: - (void)setValues:(id)values;	// 0x318af888
- (void)setValues:(id)values titles:(id)titles;	// 0x318af084
- (void)setValues:(id)values titles:(id)titles shortTitles:(id)titles3;	// 0x318af0b0
- (void)setupIconImageWithPath:(id)path;	// 0x318af268
// converted property getter: - (id)shortTitleDictionary;	// 0x318af628
// converted property getter: - (id)titleDictionary;	// 0x318af614
// converted property getter: - (id)userInfo;	// 0x318af600
// converted property getter: - (id)values;	// 0x318af6e4
@end

