/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSTableCell.h"

@interface PSTableCell : NSObject {
	id _userInfo;	// 92 = 0x5c
	BOOL _checked;	// 96 = 0x60
}
@property(retain) id userInfo;	// G=0x318b3b2c; S=0x318b3ad0; converted property
+ (id)_cellForSpecifier:(id)specifier defaultClass:(Class)aClass frame:(CGRect)frame;	// 0x318b153c
+ (int)cellTypeFromString:(id)string;	// 0x318b1288
+ (id)cellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b3364
+ (id)groupHeaderCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b313c
+ (id)segmentCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b1b88
+ (id)sliderCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b2058
+ (id)staticTextCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b562c
+ (id)switchCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b166c
+ (id)textFieldCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b25c0
+ (id)textViewCellWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b2db8
- (id)initWithFrame:(CGRect)frame specifier:(id)specifier;	// 0x318b3e1c
- (void)cellClicked:(id)clicked;	// 0x318b3b94
- (void)dealloc;	// 0x318b3e70
- (void)layoutSubviews;	// 0x318b3c2c
// converted property setter: - (void)setUserInfo:(id)info;	// 0x318b3ad0
- (void)setValueChangedTarget:(id)target action:(SEL)action userInfo:(id)info;	// 0x318b3b40
- (id)titleTextLabel;	// 0x318b3dc0
// converted property getter: - (id)userInfo;	// 0x318b3b2c
@end

@interface PSTableCell (SyntheticEvents)
- (id)_automationID;	// 0x318b4e1c
- (id)scriptingInfoWithChildren;	// 0x318b4eb4
@end

