/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <UIKit/UITextViewLegacy.h>
#import "Preferences-Structs.h"

@class PSTextViewTableCell;

@interface PSTextView : UITextViewLegacy {
	PSTextViewTableCell *_cell;	// 416 = 0x1a0
}
- (void)mouseDragged:(GSEventRef)dragged;	// 0x318b4a78
- (BOOL)resignFirstResponder;	// 0x318b4b0c
- (void)scrollToMakeCaretVisible:(BOOL)makeCaretVisible;	// 0x318b5364
- (void)setCell:(id)cell;	// 0x318b4a64
@end

