/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "NSObject.h"
#import "Preferences-Structs.h"


@protocol UITextViewLegacyDelegate <NSObject>
@optional
- (BOOL)textViewLegacy:(id)legacy shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
- (NSRange)textViewLegacy:(id)legacy willChangeSelectionFromRange:(NSRange)range toRange:(NSRange)range3;
- (void)textViewLegacyDidBeginEditing:(id)textViewLegacy;
- (void)textViewLegacyDidChange:(id)textViewLegacy;
- (void)textViewLegacyDidChangeSelection:(id)textViewLegacy;
- (void)textViewLegacyDidEndEditing:(id)textViewLegacy;
- (BOOL)textViewLegacyShouldBeginEditing:(id)textViewLegacy;
- (BOOL)textViewLegacyShouldEndEditing:(id)textViewLegacy;
@end

