/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>
#import "UIModalViewDelegate.h"

@class NSString, UIModalView;

@interface PSAlert : NSObject <UIModalViewDelegate> {
	id _delegate;	// 4 = 0x4
	id _userInfo;	// 8 = 0x8
	UIModalView *_sheet;	// 12 = 0xc
	NSString *_body;	// 16 = 0x10
	NSString *_title;	// 20 = 0x14
	NSString *_defaultButton;	// 24 = 0x18
	NSString *_alternateButton;	// 28 = 0x1c
	int _buttonClicked;	// 32 = 0x20
	BOOL _displayed;	// 36 = 0x24
}
@property(retain) NSString *alternateButton;	// G=0x318bf6d8; S=0x318bf674; converted property
@property(retain) id bodyText;	// G=0x318bf570; S=0x318bf50c; converted property
@property(retain) NSString *defaultButton;	// G=0x318bf660; S=0x318bf5fc; converted property
@property(retain) NSString *title;	// G=0x318bf5e8; S=0x318bf584; converted property
@property(retain) id userInfo;	// G=0x318bf96c; S=0x318bf908; converted property
+ (id)alertWithBodyText:(id)bodyText defaultButton:(id)button alternateButton:(id)button3;	// 0x318bfa9c
+ (void)displayAlertWithBodyText:(id)bodyText defaultButton:(id)button alternateButton:(id)button3 delegate:(id)delegate userInfo:(id)info;	// 0x318bfb38
- (id)init;	// 0x318bf310
- (id)alertSheet;	// 0x318bf6ec
- (void)alertSheet:(id)sheet buttonClicked:(int)clicked;	// 0x318bfa70
// converted property getter: - (id)alternateButton;	// 0x318bf6d8
// converted property getter: - (id)bodyText;	// 0x318bf570
- (void)dealloc;	// 0x318bf41c
// converted property getter: - (id)defaultButton;	// 0x318bf660
- (void)dismiss;	// 0x318bf980
- (void)display;	// 0x318bf700
// converted property setter: - (void)setAlternateButton:(id)button;	// 0x318bf674
// converted property setter: - (void)setBodyText:(id)text;	// 0x318bf50c
// converted property setter: - (void)setDefaultButton:(id)button;	// 0x318bf5fc
- (void)setDelegate:(id)delegate;	// 0x318bf4f8
// converted property setter: - (void)setTitle:(id)title;	// 0x318bf584
// converted property setter: - (void)setUserInfo:(id)info;	// 0x318bf908
// converted property getter: - (id)title;	// 0x318bf5e8
// converted property getter: - (id)userInfo;	// 0x318bf96c
@end

