/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <UIKit/UIKit.h>

@protocol PSBaseView <NSObject>
@property(retain) id parentController;	// converted property
@property(retain) id rootController;	// converted property
+ (BOOL)isOverlay;
- (id)initForContentSize:(CGSize)contentSize;
- (void)didLock;
- (void)didUnlock;
- (void)didWake;
- (void)handleURL:(id)url;
- (void)hideNavigationBarButtons;
- (void)insertNavigationItem:(id)item atIndex:(int)index;
- (void)insertNavigationItem:(id)item atIndexFromEnd:(int)end;
- (void)navigationBarButtonClicked:(int)clicked;
- (id)navigationItem;
- (id)navigationTitle;
// converted property getter: - (id)parentController;
- (BOOL)popController;
- (BOOL)popControllerWithAnimation:(BOOL)animation;
- (void)popNavigationItem;
- (void)popNavigationItemWithAnimation:(BOOL)animation;
- (void)pushController:(id)controller;
- (void)pushNavigationItem:(id)item;
- (void)pushNavigationItemWithTitle:(id)title;
- (id)readPreferenceValue:(id)value;
// converted property getter: - (id)rootController;
- (void)setNavigationBarEnabled:(BOOL)enabled;
// converted property setter: - (void)setParentController:(id)controller;
- (void)setPreferenceValue:(id)value specifier:(id)specifier;
- (void)setPrompt:(id)prompt;
// converted property setter: - (void)setRootController:(id)controller;
- (void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;
- (void)showNavigationBarButtons:(id)buttons :(id)arg2;
- (void)suspend;
- (id)view;
- (void)viewDidBecomeVisible;
- (void)viewTransitionCompleted;
- (void)viewWillBecomeVisible:(void *)view;
- (void)viewWillRedisplay;
- (void)willUnlock;
@end

