/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSTableCell.h"

@class NSDictionary, NSArray, UIControl, UIProgressIndicator;

@interface PSControlTableCell : PSTableCell {
	UIControl *_control;	// 100 = 0x64
	UIProgressIndicator *_progressIndicator;	// 104 = 0x68
	NSArray *_values;	// 108 = 0x6c
	NSDictionary *_titleDict;	// 112 = 0x70
}
@property(retain) UIControl *control;	// G=0x318b40e8; S=0x318b43c4; converted property
@property(assign) BOOL loading;	// G=0x318b40fc; S=0x318b4118; converted property
// converted property getter: - (id)control;	// 0x318b40e8
- (void)controlChanged:(id)changed;	// 0x318b4458
- (void)dealloc;	// 0x318b3fcc
// converted property getter: - (BOOL)loading;	// 0x318b40fc
// converted property setter: - (void)setControl:(id)control;	// 0x318b43c4
// converted property setter: - (void)setLoading:(BOOL)loading;	// 0x318b4118
- (void)setValue:(id)value;	// 0x318b4650
- (void)setValues:(id)values titleDictionary:(id)dictionary;	// 0x318b3ed0
- (id)titleTextLabel;	// 0x318b3f68
- (id)valueTextLabel;	// 0x318b3fc4
@end

