/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSViewController.h"

@class UIKeyboard, PSEditingPane, UIView;

@interface PSDetailController : PSViewController {
	UIView *_view;	// 12 = 0xc
	PSEditingPane *_pane;	// 16 = 0x10
	UIKeyboard *_keyboard;	// 20 = 0x14
	BOOL _keyboardVisible;	// 24 = 0x18
}
@property(readonly, assign) BOOL keyboardVisible;	// G=0x318b61e4; converted property
@property(retain) PSEditingPane *pane;	// G=0x318b5eb4; S=0x318b5d98; converted property
@property(readonly, retain) UIView *view;	// G=0x318b65bc; converted property
- (id)initForContentSize:(CGSize)contentSize;	// 0x318b5a10
- (void)_addKeyboardView;	// 0x318b5c2c
- (void)_updateNavBarButtons;	// 0x318b59d8
- (void)cancelButtonClicked:(id)clicked;	// 0x318b64e8
- (void)dealloc;	// 0x318b5b28
- (void)doneButtonClicked:(id)clicked;	// 0x318b64a4
// converted property getter: - (BOOL)keyboardVisible;	// 0x318b61e4
- (void)navigationBarButtonClicked:(int)clicked;	// 0x318b6518
- (id)navigationTitle;	// 0x318b63a0
// converted property getter: - (id)pane;	// 0x318b5eb4
- (void)popController;	// 0x318b6540
- (void)saveChanges;	// 0x318b63dc
- (void)setKeyboardVisible:(BOOL)visible animated:(BOOL)animated;	// 0x318b5ec8
// converted property setter: - (void)setPane:(id)pane;	// 0x318b5d98
- (void)suspend;	// 0x318b6488
// converted property getter: - (id)view;	// 0x318b65bc
- (void)viewWillBecomeVisible:(void *)view;	// 0x318b61f8
- (void)viewWillRedisplay;	// 0x318b5bac
@end

