/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <UIKit/UIPreferencesTextTableCell.h>


@interface PSEditableTableCell : UIPreferencesTextTableCell {
	id _userInfo;	// 108 = 0x6c
	SEL _targetSetter;	// 112 = 0x70
	id _realTarget;	// 116 = 0x74
}
- (void)controlChanged:(id)changed;	// 0x318b47a0
- (void)dealloc;	// 0x318b498c
- (void)setValueChangedOnReturn;	// 0x318b4884
- (void)setValueChangedTarget:(id)target action:(SEL)action userInfo:(id)info;	// 0x318b48d4
@end

