/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSViewController.h"

@class UIModalView, PSSpecifier, NSMutableDictionary, NSString, UITransitionView, UIPreferencesTable, NSArray, NSMutableArray;
@protocol PSBaseView;

@interface PSListController : PSViewController {
	NSMutableDictionary *_cells;	// 12 = 0xc
	BOOL _cachesCells;	// 16 = 0x10
	NSString *_title;	// 20 = 0x14
	UITransitionView *_view;	// 24 = 0x18
	UIPreferencesTable *_table;	// 28 = 0x1c
	NSArray *_specifiers;	// 32 = 0x20
	id<PSBaseView> _detailController;	// 36 = 0x24
	id<PSBaseView> _previousController;	// 40 = 0x28
	NSMutableArray *_controllers;	// 44 = 0x2c
	NSMutableDictionary *_specifiersByID;	// 48 = 0x30
	BOOL _keyboardWasVisible;	// 52 = 0x34
	BOOL _showingSetupController;	// 53 = 0x35
	BOOL _selectingRow;	// 54 = 0x36
	NSString *_specifierID; // 56 = 0x38
	PSSpecifier *_specifier;	// 60 = 0x3c
	NSMutableArray *_groups;	// 64 = 0x40
	NSMutableArray *_bundleControllers;	// 68 = 0x44
	BOOL _bundlesLoaded;	// 72 = 0x48
	CGRect _cellRect;	// 76 = 0x4c
	UIModalView *_alertSheet;	// 92 = 0x5c
}
@property(readonly, retain) PSSpecifier *specifier;	// G=0x318a8704; converted property
@property(retain) NSString *specifierID;	// G=0x318aaa00; S=0x318aa9ac; converted property
@property(retain) NSArray *specifiers;	// G=0x318a8858; S=0x318a8bb4; converted property
@property(readonly, retain) UIPreferencesTable *table;	// G=0x318a860c; converted property
@property(retain) NSString *title;	// G=0x318aaa68; S=0x318aaa14; converted property
@property(readonly, retain) UITransitionView *view;	// G=0x318ac5bc; converted property

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;

+ (BOOL)displaysButtonBar;	// 0x318a8498
- (id)initForContentSize:(CGSize)contentSize;	// 0x318aa35c
- (void)_addIdentifierForSpecifier:(id)specifier;	// 0x318a8918
- (BOOL)_canRemoveSpecifiers:(id)specifiers;	// 0x318a9ed4
- (void)_clearParentControllerFromChildren;	// 0x318ac5f4
- (id)_createGroupIndices:(id)indices;	// 0x318aa630
- (BOOL)_getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index groups:(id)groups;	// 0x318a9110
- (void)_insertControllerUnderSetupController:(id)controller;	// 0x318ae4bc
- (void)_loadBundleControllers; // 0x318a9fec
- (void)_removeController;	// 0x318adc10
- (void)_removeIdentifierForSpecifier:(id)specifier;	// 0x318a8af0
- (void)_setSpecifiers:(id)specifiers;	// 0x318a8b3c
- (void)_showKeyboard;	// 0x318ac400
- (void)_unloadBundleControllers;	// 0x318aa0a0
- (void)_unselectTable; // 0x318ab4a8
- (void)addSpecifier:(id)specifier;	// 0x318a99d0
- (void)addSpecifier:(id)specifier animated:(BOOL)animated;	// 0x318a99f0
- (void)addSpecifiersFromArray:(id)array;	// 0x318a9a60
- (void)addSpecifiersFromArray:(id)array animated:(BOOL)animated;	// 0x318a9a80
- (void)alertSheet:(id)sheet buttonClicked:(int)clicked;	// 0x318abe38
- (id)bundle;	// 0x318a8620
- (id)cachedCellForSpecifier:(id)specifier;	// 0x318aad60
- (id)cachedCellForSpecifierID:(id)specifierID; // 0x318aadb4
- (BOOL)containsSpecifier:(id)specifier;	// 0x318a8eec
- (void)createGroupIndices;	// 0x318aa738
- (void)dealloc;	// 0x318aa180
- (id)description;	// 0x318a855c
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifier:(id)specifier; // 0x318a909c
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierAtIndex:(int)index;	// 0x318a91c8
- (BOOL)getGroup:(int *)group row:(int *)row ofSpecifierID:(id)specifierID;	// 0x318a9038
- (void)handleURL:(id)url;	// 0x318abfec
- (int)indexOfGroup:(int)group; // 0x318a8f10
- (int)indexOfSpecifier:(id)specifier;	// 0x318a8eb4
- (int)indexOfSpecifierID:(id)specifierID;	// 0x318a8e68
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier; // 0x318a994c
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifier:(id)specifier animated:(BOOL)animated; // 0x318a9740
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId;	// 0x318a9978
- (void)insertContiguousSpecifiers:(id)specifiers afterSpecifierID:(id)anId animated:(BOOL)animated;	// 0x318a97dc
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group;	// 0x318a99a4
- (void)insertContiguousSpecifiers:(id)specifiers atEndOfGroup:(int)group animated:(BOOL)animated;	// 0x318a9858
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index;	// 0x318a9920
- (void)insertContiguousSpecifiers:(id)specifiers atIndex:(int)index animated:(BOOL)animated;	// 0x318ad434
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2;	// 0x318a96bc
- (void)insertSpecifier:(id)specifier afterSpecifier:(id)specifier2 animated:(BOOL)animated;	// 0x318a94dc
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId;	// 0x318a96e8
- (void)insertSpecifier:(id)specifier afterSpecifierID:(id)anId animated:(BOOL)animated;	// 0x318a9570
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group;	// 0x318a9714
- (void)insertSpecifier:(id)specifier atEndOfGroup:(int)group animated:(BOOL)animated;	// 0x318a95c8
- (void)insertSpecifier:(id)specifier atIndex:(int)index;	// 0x318a9690
- (void)insertSpecifier:(id)specifier atIndex:(int)index animated:(BOOL)animated;	// 0x318a9384
- (id)lastController;	// 0x318aacd8
- (id)loadSpecifiersFromPlistName:(id)plistName target:(id)target;	// 0x318a8718
- (void)loseFocus;	// 0x318aa7a8
- (void)navigationBarButtonClicked:(int)clicked;	// 0x318ac688
- (id)navigationTitle;	// 0x318aa61c
- (int)numberOfGroups;	// 0x318a8f7c
- (int)numberOfGroupsInPreferencesTable:(id)preferencesTable;	// 0x318aaaf0
- (BOOL)performActionForSpecifier:(id)specifier;	// 0x318ab860
- (BOOL)popController;	// 0x318ac5d0
- (BOOL)popControllerWithAnimation:(BOOL)animation;	// 0x318ad79c
- (id)preferencesTable:(id)table cellForGroup:(int)group;	// 0x318ab10c
- (id)preferencesTable:(id)table cellForRow:(int)row inGroup:(int)group;	// 0x318ab184
- (float)preferencesTable:(id)table heightForRow:(int)row inGroup:(int)group withProposedHeight:(float)proposedHeight;	// 0x318aaf7c
- (BOOL)preferencesTable:(id)table isLabelGroup:(int)group;	// 0x318aab44
- (int)preferencesTable:(id)table numberOfRowsInGroup:(int)group;	// 0x318aabdc
- (id)preferencesTable:(id)table titleForGroup:(int)group;	// 0x318ab06c
- (void)pushController:(id)controller;	// 0x318abfcc
- (void)pushController:(id)controller animate:(BOOL)animate;	// 0x318ae000
- (void)reload; // 0x318aa834
- (void)reloadIconForSpecifierForBundle:(id)bundle;	// 0x318ac6cc
- (void)reloadSpecifier:(id)specifier;	// 0x318a8de4
- (void)reloadSpecifier:(id)specifier animated:(BOOL)animated;	// 0x318a8d84
- (void)reloadSpecifierAtIndex:(int)index;	// 0x318a8d64
- (void)reloadSpecifierAtIndex:(int)index animated:(BOOL)animated;	// 0x318a8ca8
- (void)reloadSpecifierID:(id)anId;	// 0x318a8e48
- (void)reloadSpecifierID:(id)anId animated:(BOOL)animated;	// 0x318a8e04
- (void)reloadSpecifiers;	// 0x318aa918
- (void)removeContiguousSpecifiers:(id)specifiers;	// 0x318a9fa0
- (void)removeContiguousSpecifiers:(id)specifiers animated:(BOOL)animated;	// 0x318ace6c
- (void)removeLastSpecifier;	// 0x318a9e58
- (void)removeLastSpecifierAnimated:(BOOL)animated;	// 0x318a9e78
- (void)removeSpecifier:(id)specifier;	// 0x318a9df8
- (void)removeSpecifier:(id)specifier animated:(BOOL)animated;	// 0x318a9af0
- (void)removeSpecifierAtIndex:(int)index;	// 0x318a9e38
- (void)removeSpecifierAtIndex:(int)index animated:(BOOL)animated;	// 0x318a9bd4
- (void)removeSpecifierID:(id)anId;	// 0x318a9e18
- (void)removeSpecifierID:(id)anId animated:(BOOL)animated;	// 0x318a9b50
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2;	// 0x318a9fc0
- (void)replaceContiguousSpecifiers:(id)specifiers withSpecifiers:(id)specifiers2 animated:(BOOL)animated;	// 0x318aca10
- (int)rowsForGroup:(int)group; // 0x318a927c
- (void)selectRowWithoutNotification:(int)notification; // 0x318ab500
- (void)setCachesCells:(BOOL)cells;	// 0x318a84a0
// converted property setter: - (void)setSpecifierID:(id)anId;	// 0x318aa9ac
// converted property setter: - (void)setSpecifiers:(id)specifiers;	// 0x318a8bb4
// converted property setter: - (void)setTitle:(id)title;	// 0x318aaa14
- (void)showConfirmationSheetForSpecifier:(id)specifier;	// 0x318ab594
- (void)showKeyboardWithKeyboardType:(int)keyboardType; // 0x318ac874
// converted property getter: - (id)specifier;	// 0x318a8704
- (id)specifierAtIndex:(int)index;	// 0x318a8fd0
- (id)specifierForID:(id)anId;	// 0x318abf70
// converted property getter: - (id)specifierID;	// 0x318aaa00
// converted property getter: - (id)specifiers; // 0x318a8858
- (id)specifiersInGroup:(int)group;	// 0x318a92d4
- (void)suspend;	// 0x318aa148
// converted property getter: - (id)table;	// 0x318a860c
- (id)table:(id)table cellForRow:(int)row column:(id)column;	// 0x318aadf0
- (void)tableSelectionDidChange:(id)tableSelection;	// 0x318ab9d8
// converted property getter: - (id)title;	// 0x318aaa68
- (void)transitionViewDidComplete:(id)transitionView;	// 0x318ac560
// converted property getter: - (id)view;	// 0x318ac5bc
- (void)viewDidBecomeVisible;	// 0x318aaa7c
- (void)viewWillBecomeVisible:(void *)view;	// 0x318ab20c
- (void)viewWillRedisplay;	// 0x318aaaa8
@end

