/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import "PSListController.h"

@class PSSpecifier;

@interface PSListItemsController : PSListController {
	int _rowToSelect;	// 96 = 0x60
	BOOL _deferItemSelection;	// 100 = 0x64
	PSSpecifier *_lastSelectedSpecifier;	// 104 = 0x68
}
@property(retain) id specifiers;	// G=0x318b1118; S=0x318b0464; converted property
- (void)_addStaticText:(id)text;	// 0x318b0894
- (void)dealloc;	// 0x318b033c
- (id)itemsFromDataSource;	// 0x318b0cbc
- (id)itemsFromParent;	// 0x318b09cc
- (void)listItemSelected:(id)selected;	// 0x318b0638
- (BOOL)preferencesTable:(id)table isRadioGroup:(int)group;	// 0x318b055c
- (BOOL)preferencesTable:(id)table isRow:(int)row checkedInRadioGroup:(int)radioGroup;	// 0x318b04ec
- (void)scrollToSelectedCell;	// 0x318aff5c
- (void)setRowToSelect;	// 0x318affcc
// converted property setter: - (void)setSpecifiers:(id)specifiers;	// 0x318b0464
- (void)setValueForSpecifier:(id)specifier defaultValue:(id)value;	// 0x318b01f8
// converted property getter: - (id)specifiers;	// 0x318b1118
- (void)suspend;	// 0x318b039c
- (id)table:(id)table cellForRow:(int)row column:(id)column;	// 0x318b0568
- (void)tableSelectionDidChange:(id)tableSelection;	// 0x318b07dc
- (void)viewWillBecomeVisible:(void *)view;	// 0x318afec8
- (void)viewWillRedisplay;	// 0x318afe98
@end

