/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>
#import "Preferences-Structs.h"
#import "PSBaseView.h"

@class NSString, UINavigationBar, NSMutableSet, NSMutableArray, UIView;

@interface PSRootController : NSObject <PSBaseView> {
	UIView *_contentView;	// 4 = 0x4
	UINavigationBar *_navBar;	// 8 = 0x8
	NSMutableArray *_controllers;	// 12 = 0xc
	NSString *_title;	// 16 = 0x10
	NSString *_idStr;	// 20 = 0x14
	CGSize _size;	// 24 = 0x18
	NSString *_navBarRightButtonTitle;	// 32 = 0x20
	int _navBarRightButtonStyle;	// 36 = 0x24
	BOOL _navBarRightButtonDirty;	// 40 = 0x28
	NSMutableSet *_tasks;	// 44 = 0x2c
	BOOL _deallocating;	// 48 = 0x30
	unsigned char _hasTelephony;	// 49 = 0x31
}
@property(readonly, retain) UIView *contentView;	// G=0x318b8614; converted property
@property(readonly, retain) NSMutableArray *controllers;	// G=0x318b86a0; converted property
@property(readonly, assign) BOOL deallocating;	// G=0x318b8fe8; converted property
@property(retain) id parentController;	// G=0x318b91fc; S=0x318b86e4; converted property
@property(retain) id rootController;	// G=0x318b9430; S=0x318b942c; converted property
+ (BOOL)isOverlay;	// 0x318b86f0
+ (id)readPreferenceValue:(id)value;	// 0x318b7a24
+ (void)setPreferenceValue:(id)value specifier:(id)specifier;	// 0x318b7954
+ (void)writePreference:(id)preference;	// 0x318b76e4
- (id)initForContentSize:(CGSize)contentSize;	// 0x318b86dc
- (id)initWithTitle:(id)title identifier:(id)identifier;	// 0x318b7f30
- (void)_insertController:(id)controller atIndex:(int)index;	// 0x318b9460
- (void)_popController;	// 0x318b948c
- (void)_pushController:(id)controller;	// 0x318b9434
- (void)_removeController:(id)controller;	// 0x318b94e0
- (void)addTask:(id)task;	// 0x318b84ac
- (BOOL)busy;	// 0x318b85e0
// converted property getter: - (id)contentView;	// 0x318b8614
- (id)contentViewForTopController;	// 0x318b8628
// converted property getter: - (id)controllers;	// 0x318b86a0
- (void)dealloc;	// 0x318b9010
// converted property getter: - (BOOL)deallocating;	// 0x318b8fe8
- (void)didLock;	// 0x318b8f08
- (void)didUnlock;	// 0x318b8f78
- (void)didWake;	// 0x318b8fb0
- (void)handleURL:(id)url;	// 0x318b8924
- (BOOL)hasTelephony;	// 0x318b8ffc
- (void)hideNavigationBarButtons;	// 0x318b8d20
- (void)insertNavigationItem:(id)item atIndex:(int)index;	// 0x318b8b7c
- (void)insertNavigationItem:(id)item atIndexFromEnd:(int)end;	// 0x318b8a98
- (id)lastController;	// 0x318b7ed4
- (void)lazyLoadBundle:(id)bundle;	// 0x318b9204
- (id)navigationBar;	// 0x318b9418
- (void)navigationBar:(id)bar buttonClicked:(int)clicked;	// 0x318b8e88
- (void)navigationBar:(id)bar poppedItem:(id)item;	// 0x318b8c64
- (void)navigationBar:(id)bar pushedItem:(id)item;	// 0x318b8c48
- (BOOL)navigationBar:(id)bar shouldPopItem:(id)item;	// 0x318b86bc
- (void)navigationBarButtonClicked:(int)clicked;	// 0x318b8ecc
- (id)navigationItem;	// 0x318b8700
- (id)navigationTitle;	// 0x318b86f8
// converted property getter: - (id)parentController;	// 0x318b91fc
- (BOOL)popController;	// 0x318b89d4
- (BOOL)popControllerWithAnimation:(BOOL)animation;	// 0x318b8928
- (void)popNavigationItem;	// 0x318b8c80
- (void)popNavigationItemWithAnimation:(BOOL)animation;	// 0x318b8ca0
- (void)pushController:(id)controller;	// 0x318b8710
- (void)pushNavigationItem:(id)item;	// 0x318b8a6c
- (void)pushNavigationItemWithTitle:(id)title;	// 0x318b89f8
- (id)readPreferenceValue:(id)value;	// 0x318b7eac
// converted property getter: - (id)rootController;	// 0x318b9430
- (void)setNavigationBarEnabled:(BOOL)enabled;	// 0x318b8e2c
// converted property setter: - (void)setParentController:(id)controller;	// 0x318b86e4
- (void)setPreferenceValue:(id)value specifier:(id)specifier;	// 0x318b79fc
- (void)setPrompt:(id)prompt;	// 0x318b8e5c
// converted property setter: - (void)setRootController:(id)controller;	// 0x318b942c
- (void)setupRootListForSize:(CGSize)size;	// 0x318b8320
- (void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;	// 0x318b8d4c
- (void)showNavigationBarButtons:(id)buttons :(id)arg2;	// 0x318b8df8
- (id)specifiers;	// 0x318b86b4
- (void)suspend;	// 0x318b8ed0
- (void)taskFinished:(id)finished;	// 0x318b8510
- (void)updateNavButtons;	// 0x318b8290
- (id)view;	// 0x318b86e8
- (void)viewDidBecomeVisible;	// 0x318b9538
- (void)viewTransitionCompleted;	// 0x318b953c
- (void)viewWillBecomeVisible:(void *)view;	// 0x318b8708
- (void)viewWillRedisplay;	// 0x318b870c
- (void)willUnlock;	// 0x318b8f40
@end

