/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "Preferences-Structs.h"
#import <Foundation/NSObject.h>


@interface PSSystemConfiguration : NSObject {
	SCPreferencesRef _prefs;	// 4 = 0x4
}
+ (void)releaseSharedInstance;	// 0x318bd504
+ (id)sharedInstance;	// 0x318bd4b0
- (id)init;	// 0x318bd534
- (CFStringRef)dataServiceID;	// 0x318bd680
- (void)dealloc;	// 0x318bd5a8
- (id)interfaceConfigurationValueForKey:(CFStringRef)key serviceID:(CFStringRef)anId;	// 0x318bd9a8
- (unsigned char)lockAndSynchronize;	// 0x318bd604
- (id)protocolConfiguration:(CFStringRef)configuration serviceID:(CFStringRef)anId;	// 0x318bdc14
- (id)protocolConfigurationValueForKey:(CFStringRef)key protocolType:(CFStringRef)type serviceID:(CFStringRef)anId;	// 0x318bde0c
- (void)setInterfaceConfigurationValue:(id)value forKey:(CFStringRef)key serviceID:(CFStringRef)anId;	// 0x318bda88
- (void)setProtocolConfiguration:(id)configuration protocolType:(CFStringRef)type serviceID:(CFStringRef)anId;	// 0x318bdce8
- (void)setProtocolConfigurationValue:(id)value forKey:(CFStringRef)key protocolType:(CFStringRef)type serviceID:(CFStringRef)anId;	// 0x318bdefc
- (CFStringRef)voicemailServiceID;	// 0x318bd814
@end

