/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import <Foundation/NSObject.h>
#import "Preferences-Structs.h"
#import "PSBaseView.h"

@class PSRootController;

@interface PSViewController : NSObject <PSBaseView> {
	id<PSBaseView> _parentController;	// 4 = 0x4
	PSRootController *_rootController;	// 8 = 0x8
}
@property(retain) id parentController;	// G=0x318ae9e4; S=0x318ae9d0; converted property
@property(retain) id rootController;	// G=0x318aea0c; S=0x318ae9f8; converted property
+ (BOOL)isOverlay;	// 0x318ae9c8
- (id)initForContentSize:(CGSize)contentSize;	// 0x318ae704
- (void)didLock;	// 0x318aea8c
- (void)didUnlock;	// 0x318aea94
- (void)didWake;	// 0x318aea98
- (void)forwardInvocation:(id)invocation;	// 0x318aeb94
- (void)handleURL:(id)url;	// 0x318aeac8
- (void)hideNavigationBarButtons;	// 0x318ae8c4
- (void)insertNavigationItem:(id)item atIndex:(int)index;	// 0x318ae7e4
- (void)insertNavigationItem:(id)item atIndexFromEnd:(int)end;	// 0x318ae810
- (id)methodSignatureForSelector:(SEL)selector; // 0x318aeb04
- (void)navigationBarButtonClicked:(int)clicked;	// 0x318ae9bc
- (id)navigationItem;	// 0x318ae748
- (id)navigationTitle;	// 0x318ae740
// converted property getter: - (id)parentController;	// 0x318ae9e4
- (BOOL)popController;	// 0x318aeaf4
- (BOOL)popControllerWithAnimation:(BOOL)animation;	// 0x318aeafc
- (void)popNavigationItem;	// 0x318ae868
- (void)popNavigationItemWithAnimation:(BOOL)animation; // 0x318ae894
- (void)pushController:(id)controller;	// 0x318aea9c
- (void)pushNavigationItem:(id)item;	// 0x318ae83c
- (void)pushNavigationItemWithTitle:(id)title;	// 0x318ae7b8
- (id)readPreferenceValue:(id)value;	// 0x318aea4c
// converted property getter: - (id)rootController;	// 0x318aea0c
- (void)setNavigationBarEnabled:(BOOL)enabled;	// 0x318ae960
// converted property setter: - (void)setParentController:(id)controller;	// 0x318ae9d0
- (void)setPreferenceValue:(id)value specifier:(id)specifier;	// 0x318aea20
- (void)setPrompt:(id)prompt;	// 0x318ae990
// converted property setter: - (void)setRootController:(id)controller; // 0x318ae9f8
- (void)showLeftButton:(id)button withStyle:(int)style rightButton:(id)button3 withStyle:(int)style4;	// 0x318ae91c
- (void)showNavigationBarButtons:(id)buttons :(id)arg2; // 0x318ae8f0
- (void)suspend;	// 0x318aea88
- (id)view;	// 0x318ae9c0
- (void)viewDidBecomeVisible;	// 0x318aea78
- (void)viewTransitionCompleted;	// 0x318aea84
- (void)viewWillBecomeVisible:(void *)view;	// 0x318aea7c
- (void)viewWillRedisplay;	// 0x318aea80
- (void)willUnlock;	// 0x318aea90
@end

